.TH BigScript 1 "22.11.2023" "1.0" "BigScript man"

.SH NAME
BigScript.1 - Displays a description about BigScript task.

.SH SYNOPSIS
.B BigScript
[\fIOPTION\fR]...

.SH DESCRIPTION
This script implements TicTacToe game. You can specify your name and play with AI.

.SH OPTIONS

.TP
.B \-h
Print version message information.

.TP
.B \-v
Print the latest version of the script.

.TP
.B \-n YOUR_NAME
Use this option to specify your name.


.SH AUTHOR
Mateusz Wieczorek s197743, student at Gdansk University of Technology.